### ISSUE TITLE
Missing packages in production

### ISSUE THREAD

**Issue by nicolasleger** [Phyks/HungerGames#1]
# Step to reproduce

# Build
- `export NODE_ENV=development`
- `npm install && npm run build`

# Run in production
- `rm -r node_modules/`
- `export NODE_ENV=production`
- `npm install`
- `npm run start`

=> Error ⛔️ **Missing `webpack-merge` then `opn` `webpack` `http-proxy-middleware` `extract-text-webpack-plugin` `eslint-friendly-formatter` `html-webpack-plugin` `optimize-css-assets-webpack-plugin` `webpack-dev-middleware` `webpack-hot-middleware` `connect-history-api-fallback` packages**

**Comment by nicolasleger** [comment]
@Phyks what do you suggest, add missing packages for production ?

**Comment by Phyks** [comment]
Looks like it is simply coming from https://github.com/yarnpkg/yarn/issues/1830#issuecomment-260518880 (actually, this is for `yarn` but I think `npm` behaves the same).

You should do to run in production:

```
rm -r node_modules/
npm install
NODE_ENV=production npm run start
```

**Comment by nicolasleger** [comment]
Thanks for your quick answer.
I try your commands but got the same error on missing package.

- Did you succeed to run it in production with those command ?
- If so with which version of node and npm ?

**Comment by Phyks** [comment]
I am using Node v8.5.0 but this should not matter much. Earlier, you ran `export NODE_ENV=production`, if you are using the same terminal, then it might not work.

Could you try in a clean new terminal window to run:

```
rm -r node_modules/
npm install
NODE_ENV=production npm run start
```

It should start a dev server and work. Note that this command still starts a dev server and should not be used in production. The right way of handling a production build is to

```
npm run build
```

and then serve the resulting built files with a webserver, say nginx.

**Comment by nicolasleger** [comment]
I was confused by trying to run the server in production env.
I understand clearly now and agree, production should be serve by a static sever indeed.
Thanks
